#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Delete the ~/.zshrc file, if it exists.
if [ -a "$HOME/.zshrc" ]; then
  rm ~/.zshrc
fi

# Delete the ~/.zshenv file, if it exists.
if [ -a "$HOME/.zshenv" ]; then
  rm ~/.zshenv
fi

# Delete the ~/.vimrc file, if it exists.
if [ -a "$HOME/.vimrc" ]; then
  rm ~/.vimrc
fi

# Delete the ~/.gemrc file, if it exists.
if [ -a "$HOME/.gemrc" ]; then
  rm ~/.gemrc
fi

# Symlinks
ln -s "$DIR/zshrc" ~/.zshrc
ln -s "$DIR/zshenv" ~/.zshenv
ln -s "$DIR/vimrc" ~/.vimrc
ln -s "$DIR/gemrc" ~/.gemrc

# Delete the vim directory, if it exists.
if [ -a "$HOME/.vim" ]; then
  rm -rf ~/.vim
fi

# Create the vim and bundle directories.
mkdir -p ~/.vim/bundle

# Install Vundle.
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

# Remove the ~/.pryrc file, if it exists.
if [ -a ~/.pryrc ]; then
  rm ~/.pryrc
fi

# Symlink pryrc.
ln -s "$DIR/pryrc" ~/.pryrc
